import "./BrowserManager/index.ts"
import "./utils/virtualKeys.ts"
import "./utils/formatters/index.ts"
// import "./utils/animPlayer.js"

import "./Managers/cursorManager.ts"
import "./Authorization/authorization.ts"
import "./CharacterManager/characterManager.ts"
import "./RoomManager/roomManager.ts"
import "./Managers/colshapeManager.ts"
import "./AdminPanel/index.ts"
import "./DeathAndReborn/index.ts"
import "./GameInfo/gameInfo.ts"
