using System;

namespace AdminPanel.JsonBuilder
{
    [AttributeUsage(AttributeTargets.Method)]
    internal class AutoGeneratedAdminPanelMethodAttribute : Attribute
    {
        public string Category { get; }

        public bool IsReturnsValue { get; }

        public AutoGeneratedAdminPanelMethodAttribute(string category, bool isReturnsValue = false)
        {
            Category = category;
            IsReturnsValue = isReturnsValue;
        }
    }
}